config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :blog_posts


  # get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  
  # get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  # patch "/blog_posts/:id", to: "blog_posts#update"
  # delete "/blog_posts/:id", to: "blog_posts#destroy"
  # get "/blog_posts/:id/edit", to:"blog_posts#edit", as: :edit_blog_post
  # post "/blog_posts", to: "blog_posts#create", as: :blog_posts
  
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    validates :title, presence:true 
    validates :body, presence:true

    scope :sorted, -> {order(arel_table[:published_at].desc.nulls_last).order(updated_at: :desc)}
    scope :draft, -> {where(published_at: nil)}
    scope :published, -> {where("published_at <= ?", Time.current)}
    scope :scheduled, -> {where("published_at > ?", Time.current)}

    def draft?
        published_at.nil?
    end 
    
    def published?
        published_at? && published_at <= Time.current
    end

    def scheduled?
            published_at? && published_at > Time.current 
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def index
  

end

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :authenticate_user!, except:[:index, :show]
    # only:[:show, :edit, :update, :destroy]  <---- ONlY means for only those functions. Except means everything except functions listed. 
    before_action :set_blog_post, except:[:index, :new, :create ] 
    
    
    def index
         @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted 

    end

    def show
         
    
    end

    def new
        
        @blog_post = BlogPost.new
    end

    def create
        @blog_post = BlogPost.new(blog_post_params)
       
        if @blog_post.save
            
          flash[:success] = "Object successfully created"
          
          redirect_to @blog_post
        else
          
          flash[:error] = "Something went wrong"
          render 'new', status: :unprocessable_entity
        end
    end

    def edit
        
    end

    def update
        
        if @blog_post.update(blog_post_params)
          flash[:success] = "Blog was successfully updated"
          redirect_to @blog_post
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end

    def destroy
        
        if @blog_post.destroy
            flash[:success] = 'Object was successfully deleted.'
            redirect_to root_path
        else
            flash[:error] = 'Something went wrong'
            redirect_to blog_posts_url
        end
    end
    
    
    

    private 


    def blog_post_params
        params.require(:blog_post).permit(:title, :body, :published_at)
    end 

    def set_blog_post 
        user_signed_in? ? @blog_post = BlogPost.find(params[:id]) : @blog_post = BlogPost.published.find(params[:id]) 

        rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end
    
    # def authenticate_user
    # This function is equal more or less to what devise provides with the before_action "authenticate_user"
    #     redirect_to new_user_session_path, alert: "You must sign in or sign up to continue." unless user_signed_in?
    # end
    
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form|%>
    <% if form.object.errors.any? %>
         <% form.object.errors.full_messages.each do |message|%>
         <div><%= message%></div>
         <%end%>
    <%end%>

    <div>
        <%= form.label :title%>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :body%>
        <%= form.text_area :body%>
    </div>

    <div>
        <%= form.label :published_at %>
        <%= form.datetime_select :published_at, include_blank: true %>
    </div>

    <%= form.button %>
<%end%>

app/views/blog_posts/edit.html.erb
<h1> blog posts edit </h1>

<%= render partial: "form", locals: {blog_post: @blog_post} %>
<%= button_to "Delete", @blog_post, method: :delete, data:{turbo_confirm: "Are you sure, my guy?"} %>

app/views/blog_posts/index.html.erb
<h1 >Hello world </h1>

<% @blog_posts.each do |blog_post|  %>
    <div>
        <% if blog_post.draft? %>
            <div class="p-2 rounded bg-gray-100 text-gray-900">Draft</div>
        <% elsif blog_post.scheduled? %>
            <div class="p-2 rounded bg-blue-100 text-blue-900">Scheduled</div>
        <%end%>
        <h2> <%=  link_to  blog_post.title, blog_post %></h2>
        <%= blog_post.body %>
    </div>
<% end%>

app/views/blog_posts/new.html.erb
<h1>new blog posts</h1>

<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<div>
    
    <%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed_in? %>
    <h1> <%= @blog_post.title %> </h1>
    
    <%= @blog_post.body%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <nav >
    <ul class="flex flex-row flex-nowrap px-8">
      <li><%= link_to "Home", root_path %></li>
      <li><% if user_signed_in? %>
      <%= link_to "New blog post", new_blog_post_path %>
         <%= link_to "Profile", edit_user_registration_path %> 
        <li><%= button_to "log out", destroy_user_session_path, method: :delete %></li>
       <%# <%else%>
       <%# <%= link_to "Sign In", new_user_session_path %>
       <%# <%= link_to "Sign Up", new_user_registration_path %> 
       <%else%>
        <li><%= link_to "Sign In", new_user_session_path %></li>
         <li><%= link_to "Sign Up", new_user_registration_path %></li> 
      <%end %> </li>
    </ul>
    </nav>
  <body class="prose mx-auto ">
    
    <p class="notice px-5"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div> 
      <%# <% if user_signed_in? %>
      <%# <%= link_to "New blog post", new_blog_post_path %> 
        <%# <%= link_to "Profile", edit_user_registration_path %> 
        <%# <%= button_to "log out", destroy_user_session_path, method: :delete %> 
       <%# <%else%>
       <%# <%= link_to "Sign In", new_user_session_path %>
       <%# <%= link_to "Sign Up", new_user_registration_path %>   
      <%# <%end %>    

    </div>
    <%= yield %>
  </body>
</html>